Models/Task.cs
using Microsoft.Identity.Client;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Proj.Models.Validation;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.IdentityModel.Tokens;

namespace Proj.Models;

public static class TaskCommand
{
    public record Create(
        [Required(ErrorMessage = "Numele task-ului este obligatoriu.")]
        [StringLength(50)]
        string Name,
        [StringLength(512)]
        [Required(ErrorMessage = "Task-ul treuie sa aiba o descriere.")]
        string Description,
        [Required(ErrorMessage = "Statusul este obligatoriu.")]
        string Status,
        [Required(ErrorMessage = "Adaugati data de inceput.")]
        DateTimeOffset StartDate,
        [Required(ErrorMessage = "Adaugati data de finalizare."),
         SameOrAfter(nameof(StartDate),
             errorMessage: "Data de sfarsit trebuie sa fie dupa cea de inceput")]
        DateTimeOffset EndDate,
        [Required(ErrorMessage = "Adaugati continut.")]
        string MediaUrl,
        Guid? LabelId
    );

    public record Edit(
        Guid Id,
        [Required(ErrorMessage = "Numele task-ului este obligatoriu.")]
        [StringLength(50)]
        string Name,
        [StringLength(512)]
        [Required(ErrorMessage = "Task-ul treuie sa aiba o descriere.")]
        string Description,
        [Required(ErrorMessage = "Statusul este obligatoriu.")]
        string Status,
        [Required(ErrorMessage = "Adaugati data de inceput.")]
        DateTimeOffset StartDate,
        [Required(ErrorMessage = "Adaugati data de finalizare."),
         SameOrAfter(nameof(StartDate),
             errorMessage: "Data de sfarsit trebuie sa fie dupa cea de inceput")]
        DateTimeOffset EndDate,
        [Required(ErrorMessage = "Adaugati continut.")]
        string MediaUrl,
        Guid? LabelId
    );

    public record ChangeStatus(
        [Required] Guid TaskId,
        [Required] Guid ProjectId,
        [Required, OneOf("Not Started", "In Progress", "Done")]
        string NewStatus
    );
}

public class Task
{
    public Guid Id { get; private init; } = Guid.NewGuid();
    public string Name { get; set; }
    public string Description { get; set; }
    public string Status { get; set; }
    public DateTimeOffset StartDate { get; set; }
    public DateTimeOffset EndDate { get; set; }
    public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow;
    public DateTimeOffset? DeletedAt { get; set; }
    public string MediaUrl { get; set; }
    public Guid ProjectId { get; init; } // Required FK
    public Guid? ParentTaskId { get; init; }
    public Guid? LabelId { get; set; }
    public Label? Label { get; set; } = default;


    public virtual Project? Project { get; set; }

    // navigation property referencing the parent task (if it exists)
    [NotMapped] public virtual Task? ParentTask { get; set; }

    // collection navigation containing the subtasks for each task
    [NotMapped] public virtual ICollection<Task> Subtasks { get; } = new List<Task>();

    public virtual ICollection<Assignment>? Assignments { get; set; }

    public IEnumerable<Comment> Comments { get; set; } = new List<Comment>();

    [NotMapped] public IEnumerable<SelectListItem>? ProjectMembers { get; set; }


    Task()
    {
    }

    private Task(string name, string description, string status,
        DateTimeOffset startDate, DateTimeOffset endDate, string media, Guid projectId,
        Guid? labelId)
    {
        Name = name;
        Description = description;
        Status = status;
        StartDate = startDate;
        EndDate = endDate;
        MediaUrl = media;
        ProjectId = projectId;
        LabelId = labelId;
    }

    public static Task From(TaskCommand.Create cmd, Guid projectId)
    {
        var task = new Task(cmd.Name, cmd.Description, cmd.Status,
            cmd.StartDate, cmd.EndDate, cmd.MediaUrl, projectId, cmd.LabelId);
        return task;
    }

    /*
    public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        if (DateTimeOffset.Compare(StartDate, EndDate) == -1)
        {
            yield return ValidationResult.Success;
        }

        yield return new ValidationResult(
            "Data de inceput trebuie sa fie mai mica decat data de finalizare");
    }
    */
}

Controllers/TasksController.cs
using Ganss.Xss;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Proj.Data;
using Proj.Identity;
using Proj.Models;

namespace Proj.Controllers;

[Route("projects/{projectId:guid}/tasks")]
[Authorize(Policy = MemberRequirement.Policy)]
public class TasksController : Controller
{
    private readonly ApplicationDbContext _context;
    private readonly CurrentUser _user;

    public TasksController(ApplicationDbContext context, CurrentUser user)
    {
        _context = context;
        _user = user;
    }

    [HttpGet("{taskId:guid}")]
    public async Task<IActionResult> Show(
        [FromRoute] Guid projectId,
        [FromRoute] Guid taskId,
        CancellationToken ct = default)
    {
        if (TempData.ContainsKey("message"))
        {
            ViewBag.Message = TempData["message"];
            ViewBag.Alert = TempData["messageType"];
        }

        var task = await _context.Tasks
            .Include(t => t.Project)
            .Include(t => t.Comments)
            .ThenInclude(c => c.User)
            .Include(t => t.Label)
            .FirstOrDefaultAsync(t => !t.DeletedAt.HasValue && t.Id == taskId, ct);
        if (task is null)
        {
            return NotFound();
        }

        task.ProjectMembers = GetMembersUnassignedToTask(projectId, taskId);
        return View(task);
    }

    [HttpGet("new")]
    [Authorize(Policy = OrganizerRequirement.Policy)]
    public IActionResult New([FromRoute] Guid projectId)
    {
        ViewBag.ProjectId = projectId;
        return View();
    }

    [HttpPost("new")]
    [Authorize(Policy = OrganizerRequirement.Policy)]
    public async Task<IActionResult> New(
        [FromRoute] Guid projectId,
        [FromForm] TaskCommand.Create cmd,
        CancellationToken ct = default)
    {
        if (!ModelState.IsValid)
        {
            return View();
        }

        var task = Models.Task.From(cmd, projectId);

        var sanitizer = new HtmlSanitizer();
        task.Description = sanitizer.Sanitize(task.Description);
        await _context.Tasks.AddAsync(task, ct);
        await _context.SaveChangesAsync(ct);

        TempData["message"] = "The new task has just been successfully added.";
        TempData["messageType"] = "alert-success";
        return Redirect($"/projects/{projectId}");
    }

    [HttpGet("{taskId:guid}/edit")]
    [Authorize(Policy = OrganizerRequirement.Policy)]
    public async Task<IActionResult> Edit(
        [FromRoute] Guid projectId,
        [FromRoute] Guid taskId,
        CancellationToken ct = default)
    {
        var task = await _context.Tasks
            .FirstOrDefaultAsync(t => !t.DeletedAt.HasValue && t.Id == taskId, ct);
        if (task is null)
        {
            return NotFound();
        }

        ViewBag.ProjectId = projectId;

        return View(
            new TaskCommand.Edit(task.Id, task.Name, task.Description,
                task.Status, task.StartDate, task.EndDate,
                task.MediaUrl, task.LabelId));
    }

    [HttpPost("{taskId:guid}/edit")]
    [Authorize(Policy = OrganizerRequirement.Policy)]
    public async Task<IActionResult> Edit(
        [FromRoute] Guid projectId,
        [FromRoute] Guid taskId,
        [FromForm] TaskCommand.Edit cmd, CancellationToken ct = default)
    {
        var task = await _context.Tasks.FindAsync([taskId], ct);
        if (task is null)
        {
            return NotFound();
        }

        if (!ModelState.IsValid)
        {
            return View(new TaskCommand.Edit(task.Id, task.Name, task.Description,
                task.Status, task.StartDate, task.EndDate,
                task.MediaUrl, task.LabelId));
        }

        task.Name = cmd.Name;
        var sanitizer = new HtmlSanitizer();
        task.Description = sanitizer.Sanitize(cmd.Description);
        task.MediaUrl = cmd.MediaUrl;
        task.StartDate = cmd.StartDate;
        task.EndDate = cmd.EndDate;
        task.UpdatedAt = DateTimeOffset.UtcNow;
        task.LabelId = cmd.LabelId;

        TempData["message"] = "The task has been modified";
        TempData["messageType"] = "alert-success";

        await _context.SaveChangesAsync(ct);
        return Redirect($"/projects/{projectId}");
    }


    [HttpPost("change-status")]
    public async Task<IActionResult> ChangeStatus(
        [FromRoute] Guid projectId,
        [FromForm] TaskCommand.ChangeStatus cmd,
        CancellationToken ct = default)
    {
        var task = await _context.Tasks
            .FirstOrDefaultAsync(t => !t.DeletedAt.HasValue && t.Id == cmd.TaskId, ct);
        if (task is null)
        {
            return NotFound();
        }

        task.Status = cmd.NewStatus;
        await _context.SaveChangesAsync(ct);

        return Redirect($"/projects/{projectId}");
    }

    [HttpPost("{taskId:guid}/comment")]
    public async Task<IActionResult> Comment(
        [FromRoute] Guid projectId,
        [FromRoute] Guid taskId,
        [FromForm] CommentCommand.New cmd,
        CancellationToken ct = default)
    {
        if (!ModelState.IsValid)
        {
            return Redirect($"/projects/{projectId}/tasks/{taskId}");
        }

        var comment = new Comment(taskId, _user.Id, cmd.Content);
        await _context.Comments.AddAsync(comment, ct);
        await _context.SaveChangesAsync(ct);

        return Redirect($"/projects/{projectId}/tasks/{taskId}");
    }


    [HttpPost("{taskId:guid}/comment/{commentId:guid}")]
    public async Task<IActionResult> EditComment(
        [FromRoute] Guid projectId,
        [FromRoute] Guid taskId,
        [FromRoute] Guid commentId,
        [FromForm] CommentCommand.New cmd,
        CancellationToken ct = default)
    {
        if (!ModelState.IsValid)
        {
            return Redirect($"/projects/{projectId}/tasks/{taskId}");
        }

        var comment = await _context.Comments
            .FirstOrDefaultAsync(c => c.Id == commentId, ct);
        if (comment is null)
        {
            return NotFound();
        }

        if (!_user.IsAdmin && comment.UserId != _user.Id)
        {
            return Unauthorized();
        }

        comment.Content = cmd.Content;
        _context.Comments.Update(comment);
        await _context.SaveChangesAsync(ct);

        return Redirect($"/projects/{projectId}/tasks/{taskId}");
    }

    [HttpPost("{taskId:guid}/comment/{commentId:guid}/delete")]
    public async Task<IActionResult> DeleteComment([FromRoute] Guid projectId, Guid taskId,
        Guid commentId, CancellationToken ct = default)
    {
        var comment = await _context.Comments
            .FirstOrDefaultAsync(c => c.Id == commentId, ct);
        if (comment is null)
        {
            return NotFound();
        }

        if (!_user.IsAdmin && comment.UserId != _user.Id)
        {
            return Unauthorized();
        }

        _context.Comments.Remove(comment);
        await _context.SaveChangesAsync(ct);

        return Redirect($"/projects/{projectId}/tasks/{taskId}");
    }


    [HttpPost("{taskId:guid}/delete")]
    [Authorize(Policy = OrganizerRequirement.Policy)]
    public async Task<IActionResult> Delete(
        [FromRoute] Guid taskId,
        [FromRoute] Guid projectId,
        CancellationToken ct = default)
    {
        var task = await _context.Tasks.FindAsync([taskId], ct);
        if (task is null)
        {
            return NotFound();
        }

        task.DeletedAt = DateTimeOffset.UtcNow;
        await _context.SaveChangesAsync(ct);

        TempData["message"] = "Task deleted.";
        TempData["messageType"] = "alert-success";

        return Redirect($"/projects/{projectId}");
    }


    [HttpPost("{taskId:guid}/assign")]
    [Authorize(Policy = OrganizerRequirement.Policy)]
    public async Task<IActionResult> AssignTask(
        [FromRoute] Guid taskId,
        [FromRoute] Guid projectId,
        [FromForm] string userId,
        CancellationToken ct = default)
    {
        if (!ModelState.IsValid)
        {
            return Redirect($"/projects/{projectId}/tasks/{taskId}");
        }

        await _context.Assignments.AddAsync(new()
        {
            UserId = new Guid(userId),
            TaskId = taskId
        }, ct);
        await _context.SaveChangesAsync(ct);

        TempData["message"] = "The task was successfully assigned.";
        TempData["messageType"] = "alert-success";
        return Redirect($"/projects/{projectId}");
    }


    [NonAction]
    private IEnumerable<SelectListItem> GetMembersUnassignedToTask(Guid projectId, Guid taskId)
    {
        var selectList = new List<SelectListItem>();
        var members = _context.ApplicationUsers
            .Where(u => u.Memberships
                .Any(m => !m.EndedAt.HasValue &&
                          m.ProjectId == projectId &&
                          m.JoinedAt.HasValue))
            .Where(u => !u.Assignments
                .Any(a => a.TaskId == taskId));
        foreach (var mem in members)
        {
            selectList.Add(new SelectListItem
            {
                Value = mem.Id.ToString(),
                Text = mem.FirstName + " " + mem.LastName + " (" + mem.Email + ")"
            });
        }

        return selectList;
    }
}

Views/Tasks/Edit.cshtml
@model TaskCommand.Edit


<h2 class="mt-5">Edit task</h2>

<br />

<div class="container mt-5">

    <form method="post" asp-action="Edit" asp-controller="Tasks" asp-route-id="@Model.Id">


        <div asp-validation-summary="All" class="text-danger"></div>

        <div class="form-group">
            <label asp-for="Name" class="form-label">Name </label>
            <input asp-for="Name" class="form-control" />

            <span asp-validation-for="Name" class="text-danger"></span>
            <br />

            <vc:select-label project-id="@ViewBag.ProjectId" name="LabelId" default-label-id="@Model.LabelId"></vc:select-label>
        </div>

        <div class="form-group">
            <label asp-for="Description" class="form-label">Description</label>
            <br />
            <textarea asp-for="Description" class="form-control summernote"></textarea>

            <span asp-validation-for="Description" class="text-danger"></span>
            <br />
        </div>

        <input type="hidden" asp-for="Status" name="Status" value="Not Started" />

        <div class="form-group">
            <label asp-for="StartDate" class="form-label">Starting Date</label>
            <input type="datetime-local" asp-for="StartDate" name="StartDate" class="form-control" />
            <span asp-validation-for="StartDate" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="EndDate" class="form-label">Ending Date</label>
            <input type="datetime-local" asp-for="EndDate" name="EndDate" class="form-control" />
            <span asp-validation-for="StartDate" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="MediaUrl" class="form-label">Add a link (to a picture, video or another page):</label>
            <input type="url" asp-for="MediaUrl" name="MediaUrl" class="form-control" placeholder="https://example.com" />
            <span asp-validation-for="StartDate" class="text-danger"></span>
        </div>

        <br />
        <button class="btn btn-success" type="submit">Save changes</button>
    </form>

</div>

Views/Tasks/New.cshtml
@model TaskCommand.Create

<h2 class="text-center mt-5">New task</h2>

<br/>

<div class="container mt-5">

    <form method="post" asp-action="New" asp-controller="Tasks">

        <div asp-validation-summary="All" class="text-danger"></div>

        <div class="form-group">
            <label asp-for="Name" class="form-label">Name </label>
            <input asp-for="Name" class="form-control"/>

            <span asp-validation-for="Name" class="text-danger"></span>
            <br/>

            <vc:select-label project-id="@ViewBag.ProjectId" name="LabelId"></vc:select-label>
        </div>

        <div class="form-group">
            <label asp-for="Description" class="form-label">Description</label>
            <br/>
            <textarea asp-for="Description" class="form-control summernote"></textarea>

            <span asp-validation-for="Description" class="text-danger"></span>
            <br/>
        </div>

        <input type="hidden" asp-for="Status" name="Status" value="Not Started"/>

        <div class="form-group">
            <label asp-for="StartDate" class="form-label">Starting Date</label>
            <input type="datetime-local" asp-for="StartDate" name="StartDate" class="form-control"/>
            <span asp-validation-for="StartDate" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="EndDate" class="form-label">Ending Date</label>
            <input type="datetime-local" asp-for="EndDate" name="EndDate" class="form-control"/>
            <span asp-validation-for="StartDate" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="MediaUrl" class="form-label">Add some media (a picture from the web, a youtube video...):</label>
            <input type="url" asp-for="MediaUrl" name="MediaUrl" class="form-control" placeholder="https://example.com"/>
            <span asp-validation-for="StartDate" class="text-danger"></span>
        </div>

        <br/>
        <button class="btn btn-success" type="submit">Add Task</button>
    </form>

</div>

Views/Tasks/Show.cshtml
@using Proj.Identity
@model Proj.Models.Task
@inject CurrentUser CurrentUser

<div class="card border-success mb-3">
    <div class="card-header">
        <h3 class="card-title alert-success py-3 px-3 rounded-2">
            <b>@Model.Name</b>
            @if (Model.Label is not null)
            {
                <vc:label name="@Model.Label.Name" color="@Model.Label.Color"></vc:label>
            }
        </h3>

        <div class="d-flex justify-content-between flex-row mt-5">
            <small class="alert-success">
                <b>Starts on: @Model.StartDate.Date.ToShortDateString()</b>
            </small>

            <small class="alert-success">
                <b>Ends on: @Model.EndDate.Date.ToShortDateString()</b>
            </small>
        </div>
    </div>
    <div class="card-body p-3">


        @if (Model.Project.OrganizerId == CurrentUser.Id || CurrentUser.IsAdmin)
        {
            <form method="post" asp-controller="Tasks"
                  asp-action="AssignTask"
                  asp-route-taskId="@Model.Id"
                  asp-route-projectId="@Model.ProjectId">

                <div class="d-flex flex-row justify-content-center p-3 border-1 border-top">
                    <div class="mb-3">
                        <select class="form-select form-control" name="userId" asp-items="Model.ProjectMembers">
                            <option value="">Add a new member to this task</option>
                        </select>

                    </div>
                    <div>
                        <input type="submit" class="btn btn-success alert-success" value="+"/>
                    </div>
                </div>
            </form>
        }


        <div class="card mt-3 mb-3 p-3">
            <div class="card-text">@Html.Raw(Model.Description)</div>
        </div>
        <br/>
        <div class="d-flex align-items-center justify-content-center">
            @if (new string[] { ".png", ".jpeg", ".jpg" }.Any(m => Model.MediaUrl.Contains(m)))
            {
                <img src="@Model.MediaUrl" alt="Embedded image" width="550" height="300"/>
            }
            else if (new string[] { ".mp4", ".mov" }.Any(m => Model.MediaUrl.Contains(m)))
            {
                <video width="550" height="300" controls>
                    <source src="@Model.MediaUrl" type="video/mp4">
                    Your browser does not support the video tag.
                </video>
            }
            else
            {
                @if (!string.IsNullOrEmpty(Model.MediaUrl))
                {
                    var videoId = ExtractYouTubeVideoId(Model.MediaUrl);
                    if (videoId != null)
                    {
                        <iframe width="560" height="315" src="https://www.youtube.com/embed/@videoId" title="YouTube video player"
                                frameborder="0"
                                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                                referrerpolicy="strict-origin-when-cross-origin"
                                allowfullscreen>
                        </iframe>
                    }
                }

                @functions {

                    private string ExtractYouTubeVideoId(string url)
                    {
                        var regex = new System.Text.RegularExpressions.Regex(@"(?:youtube\.com\/(?:[^\/]+\/\S+\/|(?:v|e(?:mbed)?)\/|\S*?[?&]v=)|youtu\.be\/)([a-zA-Z0-9_-]{11})");
                        var match = regex.Match(url);
                        return match.Success ? match.Groups[1].Value : null;
                    }

                }
            }
        </div>

        @*shows comments & form to add comment*@
        <div>
            <h3 class="mb-4 mt-8">Comments</h3>

            @if (!@Model.Comments.Any())
            {
                <p class="text-muted">No comments yet. Be the first to comment!</p>
            }
            else
            {
                <ul class="list-group">
                    @foreach (var comment in @Model.Comments.OrderBy(c => c.CreatedAt))
                    {
                        <li class="list-group-item" id="comment-@comment.Id">
                            <div id="comment-content-@comment.Id" style="display: flex;" class="justify-content-between align-items-start">
                                <div>
                                    <h6 class="mb-1 text-muted">
                                        @comment.User.FirstName @comment.User.LastName
                                        <small>
                                            <i>@comment.User.Email</i>
                                        </small>
                                    </h6>
                                    <p class="mb-1">@comment.Content</p>
                                </div>

                                <div class="d-flex flex-column align-items-end">
                                    <small class="text-muted">@comment.CreatedAt.ToString("g")</small>
                                    @if (comment.UserId == CurrentUser.Id || CurrentUser.IsAdmin)
                                    {
                                        <div class="d-flex flex-row align-items-center justify-content-between">
                                            <button class="btn btn-sm btn-link" onclick="enableEdit('@comment.Id')">Edit</button>

                                            <form
                                                method="post"
                                                asp-controller="Tasks"
                                                asp-action="DeleteComment"
                                                asp-route-projectId="@Model.ProjectId"
                                                asp-route-taskId="@Model.Id"
                                                asp-route-commentId="@comment.Id">
                                                <button type="submit" class="btn btn-sm btn-danger">
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
                                                        <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5M8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5m3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0"/>
                                                    </svg>
                                                </button>
                                            </form>
                                        </div>
                                    }
                                </div>
                            </div>

                            <div id="comment-edit-@comment.Id" style="display: none;">
                                <form
                                    method="post"
                                    asp-controller="Tasks"
                                    asp-action="EditComment"
                                    asp-route-projectId="@Model.ProjectId"
                                    asp-route-taskId="@Model.Id"
                                    asp-route-commentId="@comment.Id">
                                    <textarea class="form-control mb-2" name="Content" id="edit-input-@comment.Id">@comment.Content</textarea>
                                    <button type="submit" class="btn btn-sm btn-primary">Modify</button>
                                    <button type="button" class="btn btn-sm btn-secondary" onclick="cancelEdit('@comment.Id')">Cancel</button>
                                </form>
                            </div>
                        </li>
                    }
                </ul>
                <br/>
            }

            <vc:comment-form project-id="@Model.ProjectId" task-id="@Model.Id"></vc:comment-form>

        </div>
        <br/>

        @*deletes the task*@
        @if (Model.Project.OrganizerId == CurrentUser.Id || CurrentUser.IsAdmin)
        {
            <div class="card-footer mt-10 float-right">
                <form method="post" asp-controller="Tasks" asp-action="Delete" asp-route-projectId="@Model.ProjectId" asp-route-taskId="@Model.Id">
                    <button type="submit" class="btn btn-sm btn-outline-danger h-50 w-10 p-3 float-right">Remove task</button>
                </form>
            </div>
        }

    </div>
</div>
<script>
    function enableEdit(commentId) {
        document.getElementById(`comment-content-${commentId}`).style.display = "none";
        document.getElementById(`comment-edit-${commentId}`).style.display = 'block';
    }

    function cancelEdit(commentId) {
        document.getElementById(`comment-content-${commentId}`).style.display = 'flex';
        document.getElementById(`comment-edit-${commentId}`).style.display = 'none';
    }
</script>