Models/Project.cs
using System.ComponentModel.DataAnnotations;
using Proj.Models.Validation;

namespace Proj.Models;

public static class ProjectCommand
{
    public record Create(
        [Required(ErrorMessage = "Numele proiectului este necesar")]
        [StringLength(128, MinimumLength = 1,
            ErrorMessage = "Numele nu poate avea mai mult de 128 de caractere")]
        string Name,
        [Required(ErrorMessage = "Descrierea este obligatorie")]
        [StringLength(256, MinimumLength = 1,
            ErrorMessage = "Descrierea nu poate avea mai mult de 256 de caractere")]
        string Summary
    );

    public record Edit(
        Guid Id,
        [Required(ErrorMessage = "Numele proiectului este necesar")]
        [StringLength(128, MinimumLength = 1,
            ErrorMessage = "Numele nu poate avea mai mult de 128 de caractere")]
        string Name,
        [Required(ErrorMessage = "Descrierea este obligatorie")]
        [StringLength(256, MinimumLength = 1,
            ErrorMessage = "Descrierea nu poate avea mai mult de 256 de caractere")]
        string Summary
    );

    public record InviteMember(
        Guid ProjectId,
        [Required, EmailAddress] string Email
    );

    public record HandleInvitationRespose(
        [Required] Guid ProjectId,
        [Required, OneOf("accept", "reject")] string Intent
    );
}

public class Project
{
    public Guid Id { get; private init; } = Guid.NewGuid();
    public Guid OrganizerId { get; private init; }

    public string Name { get; private set; }

    public string Summary { get; private set; }
    public DateTimeOffset CreatedAt { get; private init; } = DateTimeOffset.Now;
    public DateTimeOffset UpdatedAt { get; private set; } = DateTimeOffset.Now;
    public DateTimeOffset? DeletedAt { get; private set; }


    public ICollection<Task>? Tasks { get; set; } = new List<Task>();
    public IEnumerable<Membership> Memberships { get; private set; } = new List<Membership>();

    private Project(string name, string summary, Guid organizerId)
    {
        OrganizerId = organizerId;
        Name = name;
        Summary = summary;
    }

    // creates a new project as well as the membership of the organizer of the project
    public static (Project, Membership) From(ProjectCommand.Create cmd, Guid organizerId)
    {
        var project = new Project(cmd.Name, cmd.Summary, organizerId);
        var membership = project.AddMember(organizerId);

        return (project, membership);
    }

    public Membership AddMember(Guid userId)
    {
        if (Memberships.Any(m => m.UserId == userId))
            throw new Exceptions.ExistingMember(userId);

        return Membership.Active(userId, Id);
    }

    public Membership InviteMember(Guid userId)
    {
        if (Memberships.Any(m => m.UserId == userId))
            throw new Exceptions.ExistingMember(userId);

        return Membership.Pending(userId, Id);
    }

    public void Edit(ProjectCommand.Edit cmd)
    {
        Name = cmd.Name;
        Summary = cmd.Summary;
        UpdatedAt = DateTimeOffset.Now;
    }
}

ViewModels/ProjectsViewModels.cs
using Proj.Models;

namespace Proj.ViewModels;

public static class Projects
{
    public record Settings(
        Project Project,
        IEnumerable<Membership> Memberships);
}

Controllers/ProjectsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Proj.Data;
using Proj.Identity;
using Proj.Models;
using Proj.ViewModels;

namespace Proj.Controllers;

[Route("projects")]
public class ProjectsController : Controller
{
    private readonly ApplicationDbContext _context;
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly CurrentUser _user;

    public ProjectsController(
        ApplicationDbContext context,
        UserManager<ApplicationUser> userManager,
        CurrentUser user)
    {
        _context = context;
        _userManager = userManager;
        _user = user;
    }

    [HttpGet]
    public async Task<IActionResult> Index(CancellationToken ct = default)
    {
        if (_user.IsAdmin)
        {
            var adminProjects = await _context.Projects.ToListAsync(ct);
            return View(adminProjects);
        }

        var projects = await _context.Memberships
            .Where(m => !m.EndedAt.HasValue && m.UserId == _user.Id && m.JoinedAt.HasValue)
            .Select(m => m.Project)
            .ToListAsync(ct);

        return View(projects);
    }

    [HttpGet("{projectId:guid}")]
    [Authorize(Policy = MemberRequirement.Policy)]
    public async Task<IActionResult> Show(
        [FromRoute] Guid projectId,
        CancellationToken ct = default)
    {
        if (TempData.ContainsKey("message"))
        {
            ViewBag.Message = TempData["message"];
            ViewBag.Alert = TempData["messageType"];
        }

        var project = await _context.Projects
            .FirstOrDefaultAsync(p => !p.DeletedAt.HasValue && p.Id == projectId, ct);
        if (project is null)
        {
            return NotFound();
        }

        return View(project);
    }

    [HttpGet("new")]
    public IActionResult New() => View();

    [HttpPost("new")]
    public async Task<IActionResult> New(
        [FromForm] ProjectCommand.Create cmd,
        CancellationToken ct = default)
    {
        if (!ModelState.IsValid)
        {
            return View();
        }

        var (project, membership) = Project.From(cmd, _user.Id);
        await _context.Projects.AddAsync(project, ct);
        await _context.Memberships.AddAsync(membership, ct);
        await _context.SaveChangesAsync(ct);

        TempData["message"] = "The project has been successfully added.";
        TempData["messageType"] = "alert-success";

        return Redirect($"/projects/{project.Id}");
    }

    [HttpGet("edit/{projectId:guid}")]
    public async Task<IActionResult> Edit(
        [FromRoute] Guid projectId,
        CancellationToken ct = default)
    {
        var project = await _context.Projects.FindAsync([projectId], ct);
        if (project is null)
        {
            return NotFound();
        }

        return View(new ProjectCommand.Edit(project.Id, project.Name, project.Summary));
    }

    [HttpPost("edit/{projectId:guid}")]
    public async Task<IActionResult> Edit(
        [FromRoute] Guid projectId,
        [FromForm] ProjectCommand.Edit cmd,
        CancellationToken ct = default)
    {
        var project = await _context.Projects.FindAsync([projectId], ct);
        if (project is null)
        {
            return NotFound();
        }

        if (!ModelState.IsValid)
        {
            return View(new ProjectCommand.Edit(project.Id, project.Name, project.Summary));
        }

        project.Edit(cmd);
        await _context.SaveChangesAsync(ct);

        TempData["message"] = "The project has been modified";
        TempData["messageType"] = "alert-success";
        return Redirect($"/projects/{projectId}");
    }

    [HttpGet("{projectId:guid}/settings")]
    [Authorize(Policy = OrganizerRequirement.Policy)]
    public async Task<IActionResult> Settings(
        [FromRoute] Guid projectId,
        CancellationToken ct = default
    )
    {
        var project = await _context.Projects.FindAsync([projectId], ct);
        if (project is null)
        {
            return NotFound();
        }

        var members = await _context.Memberships
            .Where(m => m.ProjectId == projectId && !m.EndedAt.HasValue)
            .Include(m => m.User)
            .ToListAsync(ct);

        return View(new Projects.Settings(project, members));
    }

    [HttpPost("{projectId:guid}/settings/invite-member")]
    [Authorize(Policy = OrganizerRequirement.Policy)]
    public async Task<IActionResult> InviteMember(
        [FromRoute] Guid projectId,
        [FromForm] ProjectCommand.InviteMember cmd,
        CancellationToken ct = default)
    {
        var project = await _context.Projects
            .Where(p => p.Id == projectId && !p.DeletedAt.HasValue)
            .Include(p => p.Memberships)
            .FirstOrDefaultAsync(ct);
        if (project is null)
        {
            return NotFound();
        }

        if (!ModelState.IsValid)
        {
            return RedirectToAction("Settings", new { projectId });
        }

        var invitee = await _userManager.FindByEmailAsync(cmd.Email);
        if (invitee is null)
        {
            TempData["toastError"] = $"User with email address {cmd.Email} does not exist.";
            return RedirectToAction("Settings", new { projectId });
        }

        try
        {
            var invitation = project.InviteMember(invitee.Id);
            _context.Memberships.Add(invitation);
            await _context.SaveChangesAsync(ct);

            TempData["message"] = $"Invitation was sent to {cmd.Email}.";
            return RedirectToAction("Settings", new { projectId });
        }
        catch (Exceptions.ExistingMember err)
        {
            TempData["toastError"] = err.Message;
            return RedirectToAction("Settings", new { projectId });
        }
    }

    [HttpPost("{projectId:guid}/invitations")]
    public async Task<IActionResult> HandleInvitationRespose(
        [FromRoute] Guid projectId,
        [FromForm] ProjectCommand.HandleInvitationRespose cmd,
        CancellationToken ct = default
    )
    {
        if (!ModelState.IsValid)
        {
            return RedirectToAction("Index", "Inbox");
        }

        var user = await _context.ApplicationUsers
            .AsNoTracking()
            .Include(u =>
                u.Memberships.Where(m => !m.JoinedAt.HasValue))
            .FirstOrDefaultAsync(u => u.Id == _user.Id, ct);
        if (user is null)
        {
            return NotFound();
        }

        var membership = user.Memberships
            .FirstOrDefault(m => m.ProjectId == cmd.ProjectId);

        if (cmd.Intent == "accept")
        {
            var accepted = user.Accept(membership);
            _context.Entry(accepted).State = EntityState.Modified;
        }
        else
        {
            _context.Entry(membership).State = EntityState.Deleted;
        }

        await _context.SaveChangesAsync(ct);

        return RedirectToAction("Index", "Inbox");
    }

    [HttpPost("{projectId:guid}/delete")]
    [Authorize(Policy = OrganizerRequirement.Policy)]
    public async Task<IActionResult> Delete(
        [FromRoute] Guid projectId,
        CancellationToken ct = default)
    {
        var project = await _context.Projects.FindAsync([projectId], ct);
        if (project is null)
        {
            return NotFound();
        }

        _context.Projects.Remove(project);
        await _context.SaveChangesAsync(ct);

        return Redirect("/projects");
    }
}

Views/Projects/Edit.cshtml
@model ProjectCommand.Edit
@{
    Layout = "_Layout";
}

<form method="post" asp-controller="Projects" asp-action="Edit" asp-route-projectId="@Model.Id">
    <div class="form-group">
        <label asp-for="Name" class="form-label">Project name</label>
        <input asp-for="Name" class="form-control"/>
        <span asp-validation-for="Name" class="text-danger"></span>

        <br/><br/>
    </div>

    <div class="form-group">
        <label asp-for="Summary" class="form-label">Short description</label>
        <input asp-for="Summary" class="form-control"/>
        <span asp-validation-for="Summary" class="text-danger"></span>

        <br/><br/>
    </div>

    <div asp-validation-summary="All" class="text-danger"></div>

    <button class="btn btn-success" type="submit">Save changes</button>
</form>

Views/Projects/Index.cshtml
@using Proj.Identity
@model IEnumerable<Proj.Models.Project>;
@inject CurrentUser CurrentUser

@{
    Layout = "_Layout";
    ViewData["Title"] = CurrentUser.IsAdmin ? "Projects" : "My Projects";
}

<h1>@ViewData["Title"]</h1>

@if (!Model.Any())
{
    <p>You have no projects.</p>
}
else
{
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Project Name</th>
            <th>Summary</th>
            <th>Created at</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach (var project in Model)
        {
            <tr>
                <td>@project.Name</td>
                <td>@project.Summary</td>
                <td>@project.CreatedAt.Date.ToShortDateString()</td>
                <td>
                    <a class="btn btn-success" asp-controller="Projects" asp-action="Show"
                       asp-route-projectId="@project.Id">
                        View project
                    </a>
                </td>
            </tr>
        }
        </tbody>
    </table>
    <br/>
}
<a class="btn btn-success" asp-controller="Projects" asp-action="New">Create a project</a>

Views/Projects/New.cshtml
@model Proj.Models.Project

<div>
    <div>
        <div>
            <form method="post" asp-action="New" asp-controller="Projects">

                <div asp-validation-summary="All" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="Name" class="form-label">Project name</label>
                    <input asp-for="Name" class="form-control"/>
                    <span asp-validation-for="Name" class="text-danger"></span>

                    <br /><br />
                </div>


                <div class="form-group">
                    <label asp-for="Summary" class="form-label">Short description</label>
                    <input asp-for="Summary" class="form-control" />
                    <span asp-validation-for="Summary" class="text-danger"></span>

                    <br /><br />
                </div>

                <button class="btn btn-success" type="submit">Create</button>
            </form>

        </div>
    </div>
</div>

Views/Projects/Settings.cshtml
@model Proj.ViewModels.Projects.Settings

<main class="d-flex flex-column row-gap-5">

    @{
        ViewBag.Title = "Members";
        Layout = "_Layout";
    }

    @if (TempData["message"] is not null)
    {
        <h1>@TempData["message"]</h1>
    }

    <h3>@ViewBag.Title</h3>
    @if (!Model.Memberships.Any())
    {
        <p>You have no projects.</p>
    }
    else
    {
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var membership in Model.Memberships)
            {
                if (membership.UserId == membership.Project.OrganizerId)
                {
                    <tr>
                        <td>
                            <b>@membership.User.FirstName @membership.User.LastName (Organiser)</b>
                        </td>
                        <td>
                            <b>@membership.User.Email</b>
                        </td>
                    </tr>
                }
                else
                {
                    <tr>
                        <td>@membership.User.FirstName @membership.User.LastName </td>
                        <td>
                            @membership.User.Email
                            @if (membership.JoinedAt is null)
                            {
                                <span>(pending)</span>
                            }
                        </td>
                    </tr>
                }
            }
            </tbody>
        </table>
        <br/>
    }

    <vc:invite-member-form project-id="@Model.Project.Id">
    </vc:invite-member-form>

    <section>
        <h2>Labels</h2>

        <vc:labels-table project-id="@Model.Project.Id"></vc:labels-table>
    </section>

    <section>
        <h2>Danger area</h2>

        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Delete this project</h5>
                <p class="card-text">Once you delete a project, there is no going back. Please be certain.</p>

                <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteProjectModal">
                    Delete this project
                </button>

                <div class="modal fade" id="deleteProjectModal" tabindex="-1" aria-labelledby="deleteProjectModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h1 class="modal-title fs-5" id="deleteProjectModalLabel">Delete @Model.Project.Name</h1>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <h3>Are you sure?</h3>
                            </div>

                            <div class="modal-footer">
                                <form method="post" asp-controller="Projects" asp-action="Delete" asp-route-projectId="@Model.Project.Id">
                                    <button type="submit" class="btn btn-danger w-100">I want to delete this project</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>

Views/Projects/Show.cshtml
@using Proj.Identity
@model Proj.Models.Project
@inject CurrentUser CurrentUser
@{
    Layout = "_Layout";
}

@if (ViewBag.Message != null)
{
    <div class="alert @ViewBag.Alert alert-dismissible fade show p-3 rounded-3 mb-5" role="alert">
        @ViewBag.Message
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

<div class="container mt-5 mx-5">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">
                        <b>@Model.Name</b>
                    </h3>
                    <p class="card-text">@Model.Summary</p>

                    <div class="card-text text-body-secondary">
                        <small>
                            <i>Last updated: @Model.UpdatedAt.Date.ToShortDateString()</i>
                        </small>
                    </div>

                    <div class="card-footer d-flex justify-content-between">
                        @if (Model.OrganizerId == CurrentUser.Id || CurrentUser.IsAdmin)
                        {
                            <div class="p-2">
                                <a asp-controller="Projects" asp-action="Edit" asp-route-projectId="@Model.Id" class="btn btn-primary">Edit Project</a>
                            </div>

                            <div class="p-2">
                                <a asp-controller="Projects" asp-action="Settings" asp-route-projectId="@Model.Id"
                                   class="btn btn-info">
                                    Project Settings
                                </a>
                            </div>

                            <div class="p-2">
                                <a href="@Model.Id/tasks/new" class="btn btn-primary">New Task</a>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br/>

    <br/>

    <vc:tasks project-id="@Model.Id" can-edit="@(CurrentUser.Id == @Model.OrganizerId || CurrentUser.IsAdmin)"></vc:tasks>
</div>