Models/Label.cs
using System.ComponentModel.DataAnnotations;

namespace Proj.Models;

public static class LabelCommand
{
    public record Create(
        [StringLength(32)]
        [Required (ErrorMessage = "Numele etichetei este necesar.")]
        string Name,

        [Required (ErrorMessage = "Trebuie sa adaugati o culoare.")]
        [StringLength(maximumLength: 7)]
        [RegularExpression("#[A-Fa-f0-9]{6}")]
        string Color
    );
    
}
public class Label
{
    public Guid Id { get; private init; } = Guid.NewGuid();
    public Guid ProjectId { get; init; }

    public string Name { get; set; }
    public string Color { get; set; }

    public Label() { }
    private Label(string _name, string _color, Guid _projectId)
    {
        Name = _name;
        Color = _color;
        ProjectId = _projectId;
    }

    public static Label From(LabelCommand.Create cmd, Guid _projectId)
    {
        var label = new Label(cmd.Name, cmd.Color, _projectId);
        return label;
    }


}

Controllers/LabelsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Proj.Data;
using Proj.Identity;
using Proj.Models;

namespace Proj.Controllers;

[Route("projects/{projectId:guid}")]
public class LabelsController : Controller
{
    private readonly ApplicationDbContext _context;

    public LabelsController(ApplicationDbContext context)
    {
        _context = context;
    }

    [HttpGet("addlabel")]
    [Authorize(Policy = OrganizerRequirement.Policy)]
    public IActionResult New([FromRoute] Guid projectId) => View();


    [HttpPost("addlabel")]
    [Authorize(Policy = OrganizerRequirement.Policy)]
    public async Task<IActionResult> New(
        [FromRoute] Guid projectId,
        [FromForm] LabelCommand.Create cmd,
        CancellationToken ct = default)
    {
        if (!ModelState.IsValid)
        {
            return View(cmd);
        }

        var label = Label.From(cmd, projectId);
        await _context.Labels.AddAsync(label, ct);
        await _context.SaveChangesAsync(ct);

        TempData["message"] = "Label added successfully.";
        TempData["messageType"] = "alert-success";

        return Redirect($"/projects/{projectId}/settings");
    }
}

Views/Labels/New.cshtml
@model LabelCommand.Create

@{
    Layout = "_Layout";
}

<h2 class="text-center mt-5">Add a label</h2>

<br />


<div class="container mt-5">
    <form method="post" asp-controller="Labels" asp-action="New">

        <div asp-validation-summary="All" class="text-danger"></div>

        <div class="form-group">
            <label asp-for="@Model.Name" class="form-label">Name</label>
            <input asp-for="@Model.Name" class="form-control" placeholder="Add a new label..." />
            <span asp-validation-for="@Model.Name" class="text-danger"></span>
            <br />
        </div>

        <div class="form-group">
            <label asp-for="@Model.Color" class="form-label">Choose a Color:</label>
            <input asp-for="@Model.Color" type="color" class="form-control form-control-color" id="exampleColorInput"  title="Pick a color:">
            <span asp-validation-for="@Model.Color" class="text-danger"></span>
        </div>

        <div asp-validation-summary="All" class="text-danger"></div>

        <button class="btn btn-outline-success" type="submit">Add</button>
    </form>
</div>